/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

/**
 *
 * @author selecta
 */
public class TelaEscolha extends javax.swing.JFrame {

    TelaPrincipal tp = new TelaPrincipal();

    /**
     * Creates new form TelaEscolha
     */
    public TelaEscolha() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonEntidade = new javax.swing.JButton();
        jButtonPersistencia = new javax.swing.JButton();
        jButtonNegocio = new javax.swing.JButton();
        jButtonTudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("O que deseja Gerar?");

        jButtonEntidade.setBackground(new java.awt.Color(0, 136, 204));
        jButtonEntidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonEntidade.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntidade.setText("Entidade");
        jButtonEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntidadeActionPerformed(evt);
            }
        });

        jButtonPersistencia.setBackground(new java.awt.Color(0, 136, 204));
        jButtonPersistencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPersistencia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPersistencia.setText("Persistencia");
        jButtonPersistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersistenciaActionPerformed(evt);
            }
        });

        jButtonNegocio.setBackground(new java.awt.Color(0, 136, 204));
        jButtonNegocio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNegocio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNegocio.setText("Negócio");
        jButtonNegocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegocioActionPerformed(evt);
            }
        });

        jButtonTudo.setBackground(new java.awt.Color(0, 136, 204));
        jButtonTudo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTudo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTudo.setText("Tudo");
        jButtonTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonEntidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPersistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNegocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTudo)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEntidade)
                    .addComponent(jButtonPersistencia)
                    .addComponent(jButtonNegocio)
                    .addComponent(jButtonTudo))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntidadeActionPerformed
        tp.setTipo(1);
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEntidadeActionPerformed

    private void jButtonPersistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersistenciaActionPerformed
        tp.setTipo(2);
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPersistenciaActionPerformed

    private void jButtonNegocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegocioActionPerformed
        tp.setTipo(3);
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNegocioActionPerformed

    private void jButtonTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTudoActionPerformed
        tp.setTipo(4);
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscolha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntidade;
    private javax.swing.JButton jButtonNegocio;
    private javax.swing.JButton jButtonPersistencia;
    private javax.swing.JButton jButtonTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
